const test=require('node:test');const assert=require('node:assert/strict');const S=require('../frontend/js/slice-object.js');
const roi={roiId:1,vertices:[{x:-2,y:-2},{x:5,y:-2},{x:5,y:5},{x:-2,y:5}]};
const blob=(x,y)=>[[x,y],[x+.04,y],[x,y+.04],[x+.04,y+.04]];
function frame(id,xy,{timestamp=1000,frameId=10,transform=(x,y)=>[x+id,y,id]}={}){const pts=new Float32Array(xy.length*3),xyz=new Float32Array(xy.length*3);xy.forEach((p,i)=>{const w=transform(...p);pts.set([p[0],p[1],8],i*3);xyz.set(w,i*3);});return{sourceId:id,timestamp,frameId,pts,xyz};}

test('only L1 sees one object, so L1 has one slice and L2 zero',()=>{const r=S.processSliceFrame([frame(0,blob(0,0)),frame(1,blob(9,9))],{0:[roi],1:[roi]});assert.equal(r.bySensor[0].length,1);assert.equal(r.bySensor[1].length,0);});
test('same object seen by L1 and L2 remains two independent SliceObjects',()=>{const r=S.processSliceFrame([frame(0,blob(0,0)),frame(1,blob(0,0))],{0:[roi],1:[roi]});assert.equal(r.bySensor[0].length,1);assert.equal(r.bySensor[1].length,1);assert.notEqual(r.bySensor[0][0].sliceId,r.bySensor[1][0].sliceId);});
test('two objects in one ROI produce two slices per sensor',()=>{const xy=[...blob(0,0),...blob(3,3)],r=S.processSliceFrame([frame(0,xy),frame(1,xy)],{0:[roi],1:[roi]});assert.equal(r.bySensor[0].length,2);assert.equal(r.bySensor[1].length,2);});
test('one or two isolated noise points do not create slices',()=>{const r=S.processSliceFrame([frame(0,[[0,0],[1,1]])],{0:[roi]});assert.equal(r.bySensor[0].length,0);});
test('clusterEps changes clustering without algorithm changes',()=>{const xy=[[0,0],[.02,0],[.04,0],[.35,0],[.37,0],[.39,0]];assert.equal(S.processSliceFrame([frame(0,xy)],{0:[roi]},[],{clusterEps:.1}).bySensor[0].length,2);assert.equal(S.processSliceFrame([frame(0,xy)],{0:[roi]},[],{clusterEps:.5}).bySensor[0].length,1);});
test('extrinsic changes world geometry but not local geometry, including pitched Z',()=>{const xy=blob(0,0),a=S.processSliceFrame([frame(1,xy,{transform:(x,y)=>[x,y,1]})],{1:[roi]}).bySensor[1][0],b=S.processSliceFrame([frame(1,xy,{transform:(x,y)=>[x+2,y+3,1+x]})],{1:[roi]}).bySensor[1][0];assert.deepEqual(a.local,b.local);assert.notDeepEqual(a.world.center,b.world.center);assert.ok(b.world.bbox.maxZ>b.world.bbox.minZ);});
test('core dynamically supports four sensors',()=>{const frames=[0,1,2,3].map(id=>frame(id,blob(0,0))),rois=Object.fromEntries([0,1,2,3].map(id=>[id,[roi]])),r=S.processSliceFrame(frames,rois);assert.deepEqual(Object.keys(r.bySensor),['0','1','2','3']);assert.ok(Object.values(r.bySensor).every(x=>x.length===1));});
