const test=require('node:test');const assert=require('node:assert/strict');const A=require('../frontend/js/slice-association.js');
function slice(id,sensor,x,y,{roi=1,t=1000,z=sensor,wh=.4}={}){return{sliceId:id,sensorId:sensor,roiId:roi,timestamp:t,pointCount:5,world:{center:{x,y,z},bbox:{minX:x-wh/2,maxX:x+wh/2,minY:y-wh/2,maxY:y+wh/2,minZ:z,maxZ:z+.02}}};}
const frame=slices=>({timestamp:1000,bySensor:Object.groupBy(slices,s=>s.sensorId)});
test('same physical target from L1 and L2 becomes one multi-sensor object',()=>{const r=A.associateSliceFrame(frame([slice('A1',0,0,0),slice('A2',1,.05,.03,{z:2})]));assert.equal(r.multiObjects.length,1);assert.deepEqual(r.multiObjects[0].sensorIds,[0,1]);assert.equal(r.multiObjects[0].status,'multi-sensor');});
test('two targets associate without cross pairing',()=>{const r=A.associateSliceFrame(frame([slice('A1',0,0,0),slice('B1',0,3,0),slice('A2',1,.05,0),slice('B2',1,3.05,0)]));assert.equal(r.multiObjects.length,2);assert.deepEqual(r.multiObjects.map(o=>o.slices.map(s=>s.sliceId).sort()).sort(),[['A1','A2'],['B1','B2']]);});
test('single sensor slice survives as a singleton object',()=>{const r=A.associateSliceFrame(frame([slice('A1',0,0,0)]));assert.equal(r.multiObjects[0].status,'single-sensor');assert.equal(r.multiObjects[0].association.confidence,null);});
test('time, ROI and centroid gates reject invalid pairs',()=>{assert.equal(A.computeAssociationScore(slice('a',0,0,0),slice('b',1,0,0,{t:1300})).reason,'timestamp');assert.equal(A.computeAssociationScore(slice('a',0,0,0),slice('b',1,0,0,{roi:2})).reason,'different-roi');assert.equal(A.computeAssociationScore(slice('a',0,0,0),slice('b',1,2,0)).reason,'centroid-distance');});
test('same-sensor slices can never share one group',()=>{const r=A.associateSliceFrame(frame([slice('a',0,0,0),slice('b',0,.1,0),slice('c',1,.05,0)]));assert.equal(r.multiObjects.length,2);assert.ok(r.multiObjects.every(o=>new Set(o.sensorIds).size===o.sensorIds.length));});
test('Z difference is ignored by association but measured bbox preserves Z range',()=>{const r=A.associateSliceFrame(frame([slice('a',0,0,0,{z:.5}),slice('b',1,.02,0,{z:3})]));assert.equal(r.multiObjects.length,1);assert.equal(r.multiObjects[0].world.measuredBBox.minZ,.5);assert.equal(r.multiObjects[0].world.measuredBBox.maxZ,3.02);});
test('greedy conflict resolution picks highest score and scales to four sensors',()=>{const r=A.associateSliceFrame(frame([slice('a',0,0,0),slice('wrong',1,.4,0),slice('best',1,.02,0),slice('c',2,.01,.01),slice('d',3,0,.02)]));const group=r.multiObjects.find(o=>o.sensorCount===4);assert.ok(group);assert.ok(group.slices.some(s=>s.sliceId==='best'));assert.ok(!group.slices.some(s=>s.sliceId==='wrong'));});
test('disabled association preserves all slices as singleton objects',()=>{const r=A.associateSliceFrame(frame([slice('a',0,0,0),slice('b',1,.01,0)]),{enabled:false});assert.equal(r.multiObjects.length,2);assert.ok(r.multiObjects.every(o=>o.status==='single-sensor'));});
